# docker-compose.yml
version: '3.8'

services:
  whatsapp-api:
    build: .
    env_file:
      - .env
    ports:
      - "3080:8080" # puerto HTTP externo: 3080 , interno: 8080
    volumes:
      - ./session:/app/session  # Persistencia de credenciales
    environment:
      - NODE_ENV=production
      - SESSION_DIR=/app/session
      - LOGOUT_SECRET=${LOGOUT_SECRET}
      - SGIA_SECRET=${SGIA_SECRET}
      - URL_API_DIFY=${URL_API_DIFY}
      - AUTHORIZATION=${AUTHORIZATION}
      - URL=${URL}
      - URL_CEDULA=${URL_CEDULA}
      - AUTHORIZATION_NOMBRES=${AUTHORIZATION_NOMBRES}
      - URL_NOMBRES=${URL_NOMBRES}
      - URL_VERIFICAR_LOTE=${URL_VERIFICAR_LOTE}
      - AUTHORIZATION_VERIFICAR_LOTE=${AUTHORIZATION_VERIFICAR_LOTE}
      - URL_API_N8N=${URL_API_N8N}
      - AUTHORIZATION_N8N=${AUTHORIZATION_N8N}
    restart: unless-stopped